version: '3.8'
services:
  app:
    restart: always
    container_name: giveways_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2314:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    container_name: giveways_postgres
    environment:
      POSTGRES_PASSWORD: 77ZPCx0LghYju0
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    container_name: giveways_redis

volumes:
  pgdata: