version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2314:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: randompassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_server
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  pgdata: