services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://nico:admin123@db:postgres/msgiveaways
      - REDIS_HOST=redis
      - REDIS_PASSWORD=yKslTVLgulvI27nCuF1XTiwei8vapOD3
      - REDIS_USERNAME=default
      - REDIS_PORT=12345
    volumes:
      - ./app:/usr/src/app

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=msgiveaways
      - POSTGRES_USER=nico
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data